// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Address {

  city: string,
  state: string;
  country: string;
  // "government": "10 Downing Street",
  // "house_number": "10",
  // "road": "Downing Street",
  // "quarter": "Westminster",
  // "suburb": "Millbank",
  // "city": "London",
  // "state_district": "Greater London",
  // "state": "England",
  // "postcode": "SW1A 2AA",
  // "country": "United Kingdom",
  // "country_code": "gb"
}

export interface ReverseGeoCodingApiResponse {
  //  "place_id": "274058577",
  // "licence": "https://locationiq.com/attribution",
  // "osm_type": "relation",
  // "osm_id": "1879842",
  // "lat": "51.503487750000005",
  // "lon": "-0.12769645443243238",
  display_name: string;
  address: Address
  // "boundingbox": [
  //   "51.5033074",
  //   "51.5036913",
  //   "-0.1277991",
  //   "-0.1273088"
  // ]
}

export const reverseGeocodingApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://us1.locationiq.com/v1" }),
  reducerPath: "geocodingApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["ReverseGeoLocations"],
  endpoints: (build) => ({
    // Supply generics for the return type (in this case `QuotesApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    fetchGeoLocations: build.query<ReverseGeoCodingApiResponse, any>({
      query: (params) => `/reverse?key=pk.30d13a4600a3a18f68dbca1abc712d75&lat=${params.latitude}&lon=${params.longitude}&format=json&`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "ReverseGeoLocations", id }],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`

export const { useFetchGeoLocationsQuery: useReverseGeoLocationQuery } = reverseGeocodingApiSlice;
